LEX=flex
YACC=bison
CC=g++
OBJECT=main #生成的目标文件
 
$(OBJECT): lex.yy.o  y.tab.o
	$(CC) lex.yy.o y.tab.o -ll
	@./$(OBJECT) #编译后立刻运行
 
lex.yy.o: lex.yy.c  y.tab.h  
	$(CC) -c lex.yy.c
 
y.tab.o: y.tab.c   stdio.h  string.h
	$(CC) -c y.tab.c
 
y.tab.c : A.y
# bison使用-d参数编译.y文件
	$(YACC) -d A.y
 
lex.yy.c y.tab.h: A.l
	$(LEX) A.l
 
clean:
	@rm -f $(OBJECT)  *.o